import "server-only"; // 🛡️ Security Guard
import { Groq } from "groq-sdk";
import { query } from "./db";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
// const PYTHON_API = process.env.NEXT_PUBLIC_PYTHON_API;

// 🌟 THE OPENAPI TRANSLATION: Exposing ONLY the read-only GET endpoints to Groq
const readOnlyTools = [
  {
    type: "function" as const,
    function: {
      name: "executeSQL",
      description:
        "Executes a read-only PostgreSQL query to extract real-time library assets. ONLY SELECT queries are permitted.",
      parameters: {
        type: "object",
        properties: {
          sqlSentence: {
            type: "string",
            description:
              "The raw PostgreSQL query statement. Schema tables: 'books' (columns: id, title, price, pages, author_id), 'authors' (columns: id, name, bio).",
          },
        },
        required: ["sqlSentence"],
      },
    },
  },
];

export async function askLibraryAI(userPrompt: string): Promise<string> {
  const messages: any[] = [
    {
      role: "system",
      content: `You are a professional PostgreSQL database assistant. 
      Use the 'executeSQL' tool to look up data dynamically.
      CRITICAL RULE: You can only generate read-only SELECT statements. Do not alter tables.`,
    },
    { role: "user", content: userPrompt },
  ];

  // Pass 1: Send request to Groq so it can write the SQL string
  const response = await groq.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: messages,
    tools: readOnlyTools,
    tool_choice: "auto",
  });

  const responseMessage = response.choices[0].message;
  const toolCalls = responseMessage.tool_calls;

  // If Groq says: "Here is the dynamic SQL query to answer that user question"
  if (toolCalls) {
    messages.push(responseMessage);

    for (const toolCall of toolCalls) {
      const functionName = toolCall.function.name;
      const args = JSON.parse(toolCall.function.arguments);

      if (functionName === "executeSQL") {
        const rawSql = args.sqlSentence.trim();

        // 🛡️ SECURITY GUARD: Enforce read-only rules at the code level
        if (!rawSql.toLowerCase().startsWith("select")) {
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: functionName,
            content: JSON.stringify({
              error: "Security Violation: Only SELECT queries are permitted.",
            }),
          });
          continue;
        }

        try {
          // 🌟 THE HIT: Run the SQL generated by Groq directly on your pg connection string pool!
          console.log("Groq generated dynamic SQL execution request:", rawSql);
          const dbResult = await query(rawSql);

          // Feed the database result array back to the AI
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: functionName,
            content: JSON.stringify(dbResult.rows), // Node-postgres stores data inside .rows
          });
        } catch (dbError: any) {
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            name: functionName,
            content: JSON.stringify({
              error: "SQL Execution Syntax Error",
              detail: dbError.message,
            }),
          });
        }
      }
    }

    // Pass 2: Groq scans the rows returned by your postgres database and explains them in regular text
    const finalResponse = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: messages,
    });

    return finalResponse.choices[0].message.content || "No analysis generated.";
  }

  return responseMessage.content || "No analysis generated.";
}
